import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

export const metadata: Metadata = {
  title: "Quizzy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <div className="flex flex-1">
          {/* <Sidebar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
