import type { Metadata } from "next";
import Navbar from "./Navbar";
import "@/app/globals.css";
import "@/lib/utils/string.extensions";
import { cookies } from "next/headers";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Quizzy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthed = Boolean((await cookies()).get("next-auth.session-token"));
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <body
        className={`min-h-screen ${
          isAuthed ? "bg-(--background)" : "bg-white"
        } text-black transition-colors`}
      >
        <Providers>
          <Navbar />
          <div className="flex ">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
