import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import "@/styles/globals.css";
import "@/lib/utils/string.extensions";
import { Providers } from "@/providers/AppProviders";
import { GlobalDrawer } from "@/components/common/drawer/GlobalDrawer";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Quizzy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <body
        className={`min-h-screen bg-(--background) text-black transition-colors`}
      >
        <Script
          src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.4/dist/confetti.browser.min.js"
          strategy="afterInteractive"
        />
        <Providers>
          <Navbar />
          <div className="flex pt-10 lg:pt-0">{children}</div>
          <GlobalDrawer />
        </Providers>
      </body>
    </html>
  );
}
